format = """
[](purple)\
$hostname\
[](purple) \
[I am a cacahuete 🥜](green) \
$all\
""" 

#[character]
#success_symbol = '🥜'
#error_symbol = '👿'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[hostname]
ssh_only = false
trim_at = "."
style = "bg:purple fg:black"
format = "[$hostname]($style)"
